stages:
  - build

variables:
  IMAGE_PREFIX: "${CI_REGISTRY_IMAGE}"

.build-template: &build-template
  stage: build
  tags:
    - k8s
    - docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json

build-mind:
  <<: *build-template
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/mind"
      --dockerfile "${CI_PROJECT_DIR}/mind/Dockerfile"
      --destination "${IMAGE_PREFIX}/mind:latest"
      --insecure

build-ears:
  <<: *build-template
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/ears"
      --dockerfile "${CI_PROJECT_DIR}/ears/Dockerfile"
      --destination "${IMAGE_PREFIX}/ears:latest"
      --insecure
      --single-snapshot
      --snapshotMode=redo

build-mouth:
  <<: *build-template
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/mouth"
      --dockerfile "${CI_PROJECT_DIR}/mouth/Dockerfile"
      --destination "${IMAGE_PREFIX}/mouth:latest"
      --insecure

build-face:
  <<: *build-template
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/face"
      --dockerfile "${CI_PROJECT_DIR}/face/Dockerfile"
      --destination "${IMAGE_PREFIX}/face:latest"
      --insecure
